name: Run tests

on:
    pull_request:
        types: [opened, reopened, synchronize]
        branches:
            - dev
    push:
        branches:
            - dev
jobs:
    all-tests:
        permissions:
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - name: Check out Git repository
              uses: actions/checkout@v2
            - name: Setup Nodejs
              uses: actions/setup-node@v4
              with:
                  node-version: 18.12.0
                  cache: 'npm'
            - name: Install dependencies
              run: npm install
            - name: Build
              run: npm run build