name: Run tests

on:
    pull_request:
        types: [opened, reopened, synchronize]
        branches:
            - dev
    push:
        branches:
            - dev
jobs:
    run-tests:
        name: All tests
        permissions:
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - name: Check out Git repository
              uses: actions/checkout@v2
            - name: Setup Nodejs
              uses: actions/setup-node@v4
              with:
                  node-version: 18.12.0
                  cache: 'npm'
            - name: Install dependencies
              run: npm install
            - name: Build
              run: npm run build
            - name: All tests
              run: npm run test
    test-code-examples:
        name: Test inline typedoc examples
        permissions:
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - name: Check out Git repository
              uses: actions/checkout@v2
            - name: Setup Nodejs
              uses: actions/setup-node@v4
              with:
                  node-version: 18.12.0
                  cache: 'npm'
            - name: Install dependencies
              run: npm install
            - name: Build Docs
              run: npm run build && npm run docs:json
            - name: Code example tests
              run: npm run test:examples
    test-html-examples:
        name: Test HTML Examples
        permissions:
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - name: Check out Git repository
              uses: actions/checkout@v2
            - name: Setup Nodejs
              uses: actions/setup-node@v4
              with:
                  node-version: 18.12.0
                  cache: 'npm'
            - name: Install dependencies
              run: npm install
            - name: Build Docs
              run: npm run build
            - name: Code example tests
              run: npm run test:html